maps/cs_salvation.res
maps/cs_salvation.bsp
maps/cs_salvation.txt
models/palmier01.mdl
models/1hdd_sklanissan.mdl
models/YMbIBALHNK1.mdl
models/tub2.mdl
models/z_buda.mdl
models/acunits01.mdl
gfx/env/mars1bk.tga
gfx/env/mars1dn.tga
gfx/env/mars1ft.tga
gfx/env/mars1lf.tga
gfx/env/mars1rt.tga
gfx/env/mars1up.tga