sound/misc/3morti.wav
sound/misc/adica.wav
sound/misc/alo.wav
sound/misc/aol.wav
sound/misc/auu.wav
sound/misc/awwcrap.wav
sound/misc/awwcrap2.wav
sound/misc/awwman.wav
sound/misc/beback.wav
sound/misc/bisou.wav
sound/misc/beer.wav
sound/misc/brawwrr.wav
sound/misc/bleeeat.wav
sound/misc/bud.wav
sound/misc/bye_love.wav
sound/misc/capcana.wav
sound/misc/capitanul.wav
sound/misc/careestiba.wav
sound/misc/cheamaoamenii.wav
sound/misc/chicken0.wav
sound/misc/chicken1.wav
sound/misc/chicken2.wav
sound/misc/chicken3.wav
sound/misc/chicken4.wav
sound/misc/circulati.wav
sound/misc/comeagain.wav
sound/misc/cow.wav
sound/misc/decenuspui.wav
sound/misc/dinpacate.wav
sound/misc/doh.wav
sound/misc/doh2.wav
sound/misc/doh3.wav
sound/misc/doh4.wav
sound/misc/doh5.wav
sound/misc/doh6.wav
sound/misc/doh7.wav
sound/misc/dohnuts.wav
sound/misc/dohoo.wav
sound/misc/dominating.wav
sound/misc/doomed.wav
sound/misc/doublekill.wav
sound/misc/DRAGU.wav
sound/misc/dumnezeii.wav
sound/misc/er.wav
sound/misc/firstblood.wav
sound/misc/force.wav
sound/misc/godlike.wav
sound/misc/goodbye.wav
sound/misc/gtg.wav
sound/misc/haha.wav
sound/misc/headshot.wav
sound/misc/hi.wav
sound/misc/hibabe.wav
sound/misc/himan.wav
sound/misc/humiliation.wav
sound/misc/impressive.wav
sound/misc/inteligent.wav
sound/misc/kickass1.wav
sound/misc/killChicken.wav
sound/misc/killingspree.wav
sound/misc/knife_hit1.wav
sound/misc/knife_hit3.wav
sound/misc/laugh.wav
sound/misc/lol69.wav
sound/misc/maytheforce.wav
sound/misc/melcii.wav
sound/misc/monsterkill.wav
sound/misc/multikill.wav
sound/misc/nauziidesat.wav
sound/misc/nutecred.wav
sound/misc/ochii.wav
sound/misc/oneandonly.wav
sound/misc/ooorgle.wav
sound/misc/ow.wav
sound/misc/perfect.wav
sound/misc/plane_drone.wav
sound/misc/prepare.wav
sound/misc/proute.wav
sound/misc/rahat.wav
sound/misc/rampage.wav
sound/misc/safacut.wav
sound/misc/s-afacut.wav
sound/misc/sheep.wav
sound/misc/studiemprob.wav
sound/misc/sugip.wav
sound/misc/talk.wav
sound/misc/tampit.wav
sound/misc/tick_tock_1b.wav
sound/misc/tick_tock_2b.wav
sound/misc/tick_tock_3b.wav
sound/misc/uite ce e.wav
sound/misc/uitece1.wav
sound/misc/ultrakill.wav
sound/misc/unstoppable.wav
sound/misc/vaidemine.wav
sound/misc/vaimama.wav
sound/misc/vizor.wav
sound/misc/woohoo.wav
sound/misc/weis.wav
sound/misc/woohoo2.wav
sound/misc/ymca.wav
maps/de_bose.res