// de_hotpoint.res - created with RESGen v2.0 BETA 3.
// RESGen is made by Jeroen "ShadowLord" Bogers.
// For more info go to http://resgen.hltools.com
// or E-mail me at resgen@hltools.com.

// .res entries (69):
editor_1.wad
hotpoint.wad
hotpoint_2.wad
gfx/env/pasmurnoup.tga
gfx/env/pasmurnodn.tga
gfx/env/pasmurnolf.tga
gfx/env/pasmurnort.tga
gfx/env/pasmurnoft.tga
gfx/env/pasmurnobk.tga
models/buzz/buzzer_kt_derevse.mdl
models/props/topol-2.mdl
models/props/pi_treeb.mdl
models/props/pi_tree2.mdl
models/props/pi_tree3.mdl
models/props/pi_tree1.mdl
models/man/el_1.mdl
models/props/water_tower.mdl
models/props/trailer_chassis.mdl
models/props/lightpole.mdl
models/props/generator.mdl
models/props/machinery2.mdl
models/props/tank.mdl
models/props/bobik_rus-1.mdl
models/man/dom_to4ka_2.mdl
models/man/dom_to4ka_4.mdl
models/man/dom_to4ka_3.mdl
models/man/dom_to4ka_5.mdl
models/props/truck_large-brown.mdl
models/buzz/buzzer_teatp_ladasp.mdl
models/buzz/buzzer_kt_gazel.mdl
models/chernobyl/furgon_kalash.mdl
models/man/78rus_ladasp.mdl
models/man/78rus_toyota_red.mdl
models/man/78rus_ladasp_blue.mdl
models/buzz/buzzer_teatp_toyota.mdl
models/man/78rus_toyota_blue.mdl
models/man/78rus_toyota.mdl
models/man/78rus_ladasp_orange.mdl
models/man/njeep.mdl
models/man/vans.mdl
models/props/jeep-russian.mdl
models/man/hl2_apc001.mdl
sound/kvartal/car_siren-1.wav
models/man/3dm_seagull.mdl
models/props/trash_02.mdl
models/props/trash_heap.mdl
models/props/trashv01.mdl
models/props/truck_russian-large_blue.mdl
models/props/truck_large-green.mdl
sprites/black_smoke3.spr
models/props/dumpster_lidclosed_green.mdl
models/props/dumpster_lidclosed.mdl
sound/dustall/ambient_guns2.wav
sound/dustall/ambient_guns1.wav
sound/dustall/ambient_guns3.wav
sound/dustall/ambient_guns4.wav
sound/dustall/ambient_guns5.wav
sound/kvartal/car_zil.wav
sound/school/fastline_station3.wav
sound/school/mechwhine.wav
sound/school/dog4.wav
sound/school/city_sirenby.wav
sound/school/biolab_windoutside_loop.wav
sound/music/aria-angel.wav
models/man/fonar_1.mdl
models/man/dm_g_truck.mdl
models/props/clothes_rack.mdl
sprites/glow01.spr
models/props/light_bulb2.mdl
