models/de_miez/air.mdl
models/de_miez/bench.mdl
models/de_miez/bush1.mdl
models/de_miez/bush2.mdl
models/de_miez/car1.mdl
models/de_miez/car2.mdl
models/de_miez/car3.mdl
models/de_miez/car4.mdl
models/de_miez/desk_chair.mdl
models/de_miez/dragonfly.mdl
models/de_miez/flies.mdl
models/de_miez/flower1.mdl
models/de_miez/flower2.mdl
models/de_miez/lamp_street1.mdl
models/de_miez/lamp_street2.mdl
models/de_miez/pole_wires.mdl
models/de_miez/pot.mdl
models/de_miez/street_tree.mdl
maps/de_miez_beta.res