maps/de_templum.bsp
maps/de_templum.res
maps/de_templum.txt
models/plaka_shrubberyyy.mdl
models/pharaoh.mdl
models/patch2.mdl
models/maxi_vutra.mdl
models/palmbz.mdl
models/palmier_large.mdl
models/dragonfly.mdl
models/n_plant.mdl
models/fisch2.mdl
models/fisch1.mdl
models/aztec_statue.mdl
models/2x_skullpolec.mdl
models/2x_skullpolea.mdl
models/gros_oiseau.mdl
models/doofcranefin.mdl
models/mouette.mdl
sound/de_templum/ambience1.wav
sound/de_templum/ambience2.wav
sound/de_templum/ambience3.wav
sound/de_templum/ambience_inside.wav
sound/de_templum/swamp.wav
sound/de_templum/water.wav
sound/de_templum/waterfall.wav
sound/de_templum/wind.wav
gfx/env/sunset02up.tga
gfx/env/sunset02bk.tga
gfx/env/sunset02dn.tga
gfx/env/sunset02ft.tga
gfx/env/sunset02lf.tga
gfx/env/sunset02rt.tga